apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-upgrade
  version: "1.26"
  region: ap-northeast-1

managedNodeGroups:
  - name: "ng"
    desiredCapacity: 1

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
